@ECHO OFF
SET PROJECT_ROOT=%~p0
CALL %PROJECT_ROOT%\venv\Scripts\activate.bat
SET PYTHONPATH=%PROJECT_ROOT%src;%PROJECT_ROOT%tests
SET NATUREREC_SAME_PAGE_REPORT=""

ECHO Project root      = %PROJECT_ROOT%
ECHO Python Path       = %PYTHONPATH%

behave
ECHO ON
